#!/bin/csh
# vim:set ts=8 sts=2 sw=2 tw=0:
#
# Last Change: 16-May-2002.
# Written By:  MURAOKA Taro <koron@tka.att.ne.jp>

set pkgname = "cmigemo"
set pkgverex = ""
set cvsproj = "lib/migemo"
set cvsroot = ":local:/cvs"
set cvscmd = "c:/cygwin/bin/cvs"

if ($1 != '') then
  set pkgver = "$1"
else if (-e VERSION) then
  set pkgver = `cat VERSION`
else
  echo ""
  echo "Please specify package version string."
  echo "Example: './mkpkg 1.0-xxx '"
  exit
endif

set pkgdir = "${pkgname}-${pkgver}${pkgverex}"
echo "${pkgdir}: "
cd ..
rm -rf "$pkgdir"

echo -n "  Making package dir ..."
${cvscmd} -d "${cvsroot}" -Q export -D now -d "$pkgdir" "$cvsproj"
echo "finish"

##############################################################################
# for Microsoft Visual Studio project files
find "$pkgdir" -name "*ds[pw]" -exec qkc -q -m \{\} \;
##############################################################################

echo -n "  Archiving ..."
tar cf "${pkgdir}.tar" "$pkgdir"
echo "finish"

echo -n "  Compressing ..."
bzip2 -f "${pkgdir}.tar"
echo "finish"

echo ""
rm -rf "$pkgdir"
if ("$version" =~ *Win*) then
  start .
else if ("$version" =~ *darwin*) then
  open .
endif
