name: CI on Linux

on:
  workflow_call:

jobs:

  build:

    name: Build

    strategy:
      matrix:
        include:
        - { arch: aarch64, runner: ubuntu-24.04-arm, }
        - { arch: x86_64,  runner: ubuntu-latest,    }

    runs-on: ${{ matrix.runner }}

    steps:

    - uses: actions/checkout@v7

    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel

    - name: Test
      run: cmake --build build --target test

    - name: Profiling
      run: |
        cmake --build build --target profile
        mkdir -p tmp/profile-linux-${{ matrix.arch }}
        cp build/bench/profile*.log tmp/profile-linux-${{ matrix.arch }}

    - name: Packaging
      run: |
        cmake --build build --target package --parallel

    - name: List files in build
      run: tree -Fh build

    - name: Upload profiling logs
      uses: actions/upload-artifact@v7
      with:
        name: profile-linux-${{ matrix.arch }}
        path: tmp/profile-linux-${{ matrix.arch }}

    - name: Upload the package
      uses: actions/upload-artifact@v7
      with:
        path: build/cmigemo-*-linux-${{ matrix.arch }}.tar.gz
        archive: false
