name: CI on WebAssembly

on:
  workflow_call:

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v7

    - name: Set up Emscripten SDK
      uses: mymindstorm/setup-emsdk@v16

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 'latest'

    - name: Build
      run: |
        emcmake cmake -B build-wasm -DBUILD_DICT=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build build-wasm

    - name: Test
      run: node wasm/test/test.js

    - name: Packaging
      id: packaging
      run: |
        VERSION=$(grep -w MIGEMO_VERSION build-wasm/src/include/migemo.h | cut -d '"' -f 2)
        PRERELEASE=$(grep -w MIGEMO_VERSION_PRERELEASE build-wasm/src/include/migemo.h | cut -d '"' -f 2)
        FULL_VER="${VERSION}${PRERELEASE}"

        PKG_NAME="cmigemo-${FULL_VER}-wasm"
        PKG_DIR="build-wasm/${PKG_NAME}"
        mkdir -p "$PKG_DIR"
        cp build-wasm/bin/migemo_wasm.* "$PKG_DIR"
        cp wasm/index.js wasm/library.js wasm/demo.html "$PKG_DIR"
        mkdir -p "$PKG_DIR/dict"
        cp -r build-wasm/dict/utf-8/. "$PKG_DIR/dict/"
        ( cd build-wasm && zip -r "${PKG_NAME}.zip" "$PKG_NAME" )

    - name: List files in build
      run: tree -Fh build-wasm

    - name: Upload the package
      uses: actions/upload-artifact@v7
      with:
        path: build-wasm/cmigemo-*-wasm.zip
        archive: false
