name: CI on Windows (MSYS2)

on:
  workflow_call:

jobs:

  build:

    name: Build

    runs-on: windows-2025-vs2026

    defaults:
      run:
        shell: cmd

    steps:
    - name: Set up MSYS2 packages
      uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
      id: msys2
      with:
        msystem: MSYS
        update:  true
        release: false
        pacboy: >-
          cmake:
          make:
          gcc:
          iconv:
          gzip:
          perl:
          tree:

    - uses: actions/checkout@v7

    - name: Build
      shell: msys2 {0}
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel

    - name: Test
      shell: msys2 {0}
      run: cmake --build build --target test

    - name: Profiling
      shell: msys2 {0}
      run: |
        cmake --build build --target profile
        mkdir -p tmp/profile-windows-msys-amd64
        mv build/profile*.log tmp/profile-windows-msys-amd64

    - name: Packaging
      shell: msys2 {0}
      run: |
        cmake --build build --target package --parallel

    - name: List files in build
      shell: msys2 {0}
      run: tree -Fh build

    - name: Upload profiling logs
      uses: actions/upload-artifact@v7
      with:
        name: profile-windows-msys-amd64
        path: tmp/profile-windows-msys-amd64

    - name: Upload the package
      uses: actions/upload-artifact@v7
      with:
        path: build/cmigemo-*.tar.gz
        archive: false
