name: CI

on: [push]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    name: Linux (Ubuntu)
    uses: ./.github/workflows/ci-linux.yml
    secrets: inherit

  macos:
    name: macOS
    uses: ./.github/workflows/ci-macos.yml
    secrets: inherit

  windows-ucrt64:
    name: Windows (UCRT64)
    uses: ./.github/workflows/ci-windows-ucrt64.yml
    secrets: inherit

  windows-msvc:
    name: Windows (MSVC)
    uses: ./.github/workflows/ci-windows-msvc.yml
    secrets: inherit

  windows-msys2:
    name: Windows (MSYS2)
    uses: ./.github/workflows/ci-windows-msys2.yml
    secrets: inherit

  wasm:
    name: WebAssembly
    uses: ./.github/workflows/ci-wasm.yml
    secrets: inherit

  release:
    name: Create release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - linux
    - macos
    - windows-ucrt64
    - windows-msvc
    - windows-msys2
    - wasm
    steps:

    - uses: actions/download-artifact@v8
      with:
        pattern: cmigemo-*
        merge-multiple: true
        skip-decompress: true

    - name: List files in build
      run: tree -Fh .

    - name: Release
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        draft: true
        prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
        files: |
          *.tar.gz
          *.zip
        fail_on_unmatched_files: true
        generate_release_notes: true
        append_body: true
